### ISSUE TITLE
Migrate from Jasmine to Mocha

### ISSUE THREAD

**Issue by jccguimaraes** [jccguimaraes/project-viewer-plus#2]
look into branch `atom-mocha-test-runner`.

The problem with the migration is because `atom-mocha-test-runner` does not load any package.
Also the `atom.packages.getPackageDirPaths()` is set to a temporary folder. So no luck here.

This is a known issue with `atom-mocha-test-runner`.

This package may only be suited for testing the code with atom API itself but not with the actual package loading. 😢

**Comment by jccguimaraes** [comment]
@Hammster, do you think it is worth investigating into this? Or just stick to old Jas 1.3?

**Comment by Hammster** [comment]
@jccguimaraes in my experience mocha tends to introduce a higher technical debt since it depends on Enzyme and Chai. It comes down if you see assertion tests that are out of the normal scope since that is the topic where Mocha excels Jasmine.

If it is Atom specific i only made experience with jasmine so i don't really know if we should switch or keep the old testing suit.

**Comment by jccguimaraes** [comment]
I don't mind Jasmine, been using Jasmine and Mocha. I just hate the fact that it is locked to 1.3 and the async is somewhat painful.

There is a small suit of Jas at the moment at the `spec` folder which is working properly.

But the ideia to use Babel and get stuck on Jasmine just makes me 🤕 !

But if the constraint of not being able to load dev packages is a ~NO GO~.

So...

Until we don't find any intel on this. The branch will be untouched. Agree @Hammster ?

**Comment by Hammster** [comment]
I agree, in the worst case we just have to transpile the tests by hand.

**Comment by jccguimaraes** [comment]
After reading the changes into Atom `1.23.0` I got to this [package](https://github.com/Alhadis/Atom-Mocha).

**Comment by cgalvarez** [comment]
Hi @jccguimaraes ! Is this package the one you want to cover with `atom-mocha`?

I can prepare a minimum PR with the right setup to get the code coverage running with my package `atom-coverage`. Let me know if you are interested ;-)

BTW, I'm working on my own fork of [`project-manager`](https://github.com/danielbrodin/atom-project-manager), which I've called [`projects`](https://github.com/cgalvarez/atom-projects). If both projects (yours and mine) has the same goals maybe we could join efforts!

I want to add some new features like:

- Code coverage (of course!, already implemented in `projects`).
- Enabling **only** the desired packages per project (still pending, currently only supports *disabling* the desired ones).
- Provide feedback to users when using wrong config files (currently working on this).
- Update all dependencies (it uses `etch` + `mobx`, although I haven't used React previously, so it's time to learn something new!)
- Automate cloud service analyses: security, quality,..., like I've done with [`atom-coverage`](https://github.com/cgalvarez/atom-coverage).

I still have to push my changes to GitHub, but I'm going to work on it actively on next days.

**Comment by jccguimaraes** [comment]
Hi @cgalvarez,

Yes, this is the package! 📦 

I have some pending tests that are using mocha and will commit and it would be actually really great if you could open the PR.

It would be interesting to see if our paths converge.

If you want to test this package and see if it makes sense for you just let me know.
I have been following your `atom-coverage` but haven't yet found the time to dive into it.

**Comment by jccguimaraes** [comment]
Closing as integration is completed
