### ISSUE TITLE
Core config override for each project

### ISSUE THREAD

**Issue by jccguimaraes** [jccguimaraes/project-viewer-plus#4]
# Scope

Allow for each project to be able to override core configurations such as **line-length indicator**.

## Current workflow

None.

- This should be implemented in the local database file such as:

```json
"projects": [
    {
      "name": "project-name",
      "icon": "project-icon",
      "paths": [
        "/path/to/project"
      ],
      "config": {}
    }
  ]
```

- Or even at the group level if all projects underneath it share the same configuration (more complex).

**Comment by Hammster** [comment]
Maybe we should encourage the use of the `.editorconfig` file for this? Since it is already widely used even outside the scope of atom and vscode.

**Comment by jccguimaraes** [comment]
I would agree with you because i can't live without .editorconfig and `editorconfig` package :) but the fact is that at least with `line-height` in the `Editor` config, the CSS line isn't compliant with that per project option.

But thinking about it, this can be `Atom` related issues.

**Comment by tanxestudio** [comment]
Sorry, I am new here, don't know how to send you private message, know its not good place to write you. I am very excited to see your new project in dock, project viewer was just very very awesome, when you are going to finish pvplus :)

**Comment by jccguimaraes** [comment]
hi @wasimxe i created the gitter channel so we can discuss about this :)

[![Gitter](https://badges.gitter.im/jccguimaraes/project-viewer-plus.svg)](https://gitter.im/jccguimaraes/project-viewer-plus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
