### ISSUE TITLE
"add path" button does nothing

### ISSUE THREAD

**Issue by cysabi** [jccguimaraes/project-viewer-plus#43]
on Fedora 30 Workstation, first of all, when I hit "Open Editor" I see no "create project" button. second, the "add path" button does absolutely nothing. The package looked promising until I tried to actually use it.
![Screenshot from 2019-06-02 17-54-38](https://user-images.githubusercontent.com/47790183/58767881-8c13b580-855f-11e9-886b-50d0bd664ddd.png)

**Comment by jccguimaraes** [comment]
hello @LeptoSpira, this is a really alpha version of the older brother `atom-project-viewer`.
Having said that, a lot of functionalities are still not developed / finished. I just published so I could get more insight from whoever wished to use this package (develop this package).

To be honest I was about to give up on the package.

I just ask you to wait a bit or a lot until it's finished...
