### ISSUE TITLE
Possible better database file

### ISSUE THREAD

**Issue by cysabi** [jccguimaraes/project-viewer-plus#44]
so the current database file example looks like this:
```json
// project-viewer-plus.json
{
  "groups": [
    {
      "name": "project-name",
      "icon": "default-icon",
      "sortBy": "position",
      "groups": [
        {
          "name": "project-name",
          "icon": "default-icon",
          "sortBy": "alphabetically",
          "groups": [],
          "projects": []
        }
      ],
      "projects": []
    }
  ],
  "projects": [
    {
      "name": "project-name",
      "icon": "default-icon",
      "paths": [
        "/path/to/project"
      ]
    }
  ]
}
```
here is how I would refactor it:
```
// project-viewer-plus.json
{
  "project-name": {
      "icon": "default-icon",
      "sortBy": "position",
      "children": {
          "project-name": {
              "icon": "default-icon",
              "sortBy": "alphabetically",
              "paths": ["/path/to/project"],
          },
    "project-name": {
      "icon": "default-icon",
      "sortBy": "alphabetically",
      "paths": ["/path/to/project"],
    }
}

```
The way this can work is if we make `paths` and `children` values optional. That means, just like with the old project viewer, if you have no path, it doesn't break. Likewise, if you have no "children" key, it will assume it is a project and not a group. If you have a "children" and "paths" key, you can auto remove the path key when you parse the file.

**Comment by jccguimaraes** [comment]
ATM i will not change this because it will make me loose even more time on the "state machine" which is something I don't want to right now. If this package get finished.

This is something that we can have a look in the future
